### ISSUE TITLE
Sesssion vs Profile error

### ISSUE THREAD

**Issue by mattfaluotico** [syn-ack-zack/ProjectBookup#15]
When logging in, the user is sent to `local.../sessions`
But when clicking profile, the user is sent to `local.../profile`

What is the difference?

**Comment by neilmadsen** [comment]
I believe its the fact that logging in takes place through the sessions
controller and it simply has the profile page rendered. That should
probably be changed to a redirect then for consistency.

**Comment by mattfaluotico** [comment]
Im more confused on how it happens, it doesn't show it in the routes.rb file

**Comment by neilmadsen** [comment]
The login goes through the create method in sessions by default because the
form sends a post to the sessions controller. The default route to the
create method is /sessions and the method simply renders the profile page
at the location
